### PR TITLE
fix output value for tidy suppression

### PR DESCRIPTION
**Pull request by ThomasHepworth**
Adds a fix for `simple_suppression`, which wasn't producing the intended output suppression values.

### CODE REVIEW

**Comment by Th368MoJ** [comment]
Output:

Screenshot 2022-04-05 at 17 11 52

**Comment by dedzo** [comment]
Thanks Tom.I deleted the old version and reinstalled it from github. However, I am still getting the same error.

**Comment by Th368MoJ** [comment]
Fixed on my end. Did you refresh your RStudio instance?
Screenshot 2022-04-05 at 17 55 37

**Comment by Th368MoJ** [comment]
Looks like my column selection is wonky for that function too 😂... ah joy

**Comment by dedzo** [comment]
Morning Tom, so I am now getting the same result as you when I run it in a reprex see below. However when I run it outside of the reprex I seem to be getting the old result. Am I doing something wrong?

``` r
renv::install('moj-analytical-services/mojSuppression', force = TRUE)
#> Installing mojSuppression [0.0.2] ...
#>  OK [linked cache]

library(mojSuppression)

table  <-dplyr::tibble(
  x = c(1, 3, 1, 5, 1, 6),
  y = c(2, 2, 7, 9, 7, 10),
  z = c(2, 5, 8, 2, 2, 11),
  a = c(5, 6, 2, 4, 1, 10),
  b = c(5, 5, 5, 5, 5, 5)
)

simple_suppression(df = table,
                   where_to_suppress = c("col"),
                   #cols_to_suppress = NULL,
                   suppression_thres = 5,
                   inc_secondary_suppression = T,
                   suppression_output_value = "~",
                   secondary_suppress_0 = T)
#> # A tibble: 6 × 5
#>   x     y     z     a     b    
#>   <chr> <chr> <chr> <chr> <chr>
#> 1 ~     ~     ~     ~     ~    
#> 2 ~     ~     ~     6     ~    
#> 3 ~     7     8     ~     ~    
#> 4 ~     9     ~     ~     ~    
#> 5 ~     7     ~     ~     ~    
#> 6 6     10    11    10    ~
```

**Pull request merged**
